// This file was generated by [rspc](https://github.com/specta-rs/rspc). Do not edit this file manually.

export type Procedures = {
    queries: 
        { key: "channels.listChannels", input: string, result: ChannelResponse[] } | 
        { key: "chat.listFriends", input: never, result: FriendResponse[] } | 
        { key: "messages.getHistory", input: HistoryQuery, result: PaginatedMessagesResponse } | 
        { key: "servers.listMyServers", input: never, result: ServerResponse[] } | 
        { key: "version", input: never, result: string },
    mutations: 
        { key: "auth.login", input: LoginRequest, result: AuthResponse } | 
        { key: "auth.register", input: RegisterRequest, result: AuthResponse } | 
        { key: "channels.create", input: CreateChannelRequest, result: ChannelResponse } | 
        { key: "channels.delete", input: DeleteChannelRequest, result: null } | 
        { key: "chat.block", input: FriendActionRequest, result: null } | 
        { key: "chat.openDm", input: DirectMessageRequest, result: DmChannelResponse } | 
        { key: "chat.requestOrAccept", input: FriendActionRequest, result: null } | 
        { key: "servers.create", input: CreateServerRequest, result: ServerResponse } | 
        { key: "servers.delete", input: DeleteServerRequest, result: null } | 
        { key: "servers.join", input: JoinServerRequest, result: ServerResponse } | 
        { key: "servers.kick", input: KickMemberRequest, result: null } | 
        { key: "servers.leave", input: LeaveServerRequest, result: null },
    subscriptions: never
};

export type AuthResponse = { id: string; username: string; email: string; token: string }

export type ChannelResponse = { id: string; name: string; server_id: string; channel_type: string }

export type CreateChannelRequest = { name: string; server_id: string; channel_type: string }

export type CreateServerRequest = { name: string }

export type DeleteChannelRequest = { channel_id: string }

export type DeleteServerRequest = { server_id: string }

export type DirectMessageRequest = { target_user_id: string }

export type DmChannelResponse = { channel_id: string }

export type FriendActionRequest = { target_username_or_email: string }

export type FriendResponse = { id: string; friend_id: string; username: string; email: string; status: string }

export type HistoryQuery = { channel_id: string; cursor: string | null; limit: number | null }

export type JoinServerRequest = { server_id: string }

export type KickMemberRequest = { server_id: string; target_user_id: string }

export type LeaveServerRequest = { server_id: string }

export type LoginRequest = { identifier: string; password: string }

export type MessageResponse = { id: string; channel_id: string; user_id: string; username: string; content: string; created_at: string }

export type PaginatedMessagesResponse = { items: MessageResponse[]; next_cursor: string | null }

export type RegisterRequest = { username: string; email: string; password: string }

export type ServerResponse = { id: string; name: string; owner_id: string }
